import type { MuseBubble } from '@/src/features/recommendations/bubbles/types';

export const MUSE_BUBBLES: MuseBubble[] = [
  {
    id: 'amber',
    label: 'amber',
    note: 'glow, warmth, late light',
    values: { color: 'gold', mood: 'warm' },
    focuses: ['balanced', 'warmer'],
  },
  {
    id: 'dusk',
    label: 'dusk',
    note: 'blue hour, slow edges',
    values: { color: 'blue', mood: 'melancholic' },
    focuses: ['balanced', 'nocturnal'],
  },
  {
    id: 'lucid',
    label: 'lucid',
    note: 'clear lines, alert air',
    values: { mood: 'focused', genre: 'classical' },
    focuses: ['focused', 'balanced'],
  },
  {
    id: 'rainlit',
    label: 'rainlit',
    note: 'wet reflections, cool drift',
    values: { color: 'blue', mood: 'dreamy', genre: 'ambient' },
    focuses: ['nocturnal', 'balanced'],
  },
  {
    id: 'soft-static',
    label: 'soft static',
    note: 'haze, grain, suspended motion',
    values: { genre: 'ambient', mood: 'dreamy' },
    focuses: ['balanced', 'surprising'],
  },
  {
    id: 'shoreline',
    label: 'shoreline',
    note: 'open water, pale distance',
    values: { country: 'iceland', genre: 'ambient', color: 'white' },
    focuses: ['balanced', 'nocturnal'],
  },
  {
    id: 'midnight-drive',
    label: 'midnight drive',
    note: 'after-hours motion, city lights',
    values: { activity: 'walking', color: 'black', mood: 'dreamy', genre: 'electronic' },
    focuses: ['nocturnal', 'surprising'],
  },
  {
    id: 'paper-moon',
    label: 'paper moon',
    note: 'tender glow, remembered scene',
    values: { lyricalTheme: 'longing', mood: 'dreamy', genre: 'jazz' },
    focuses: ['balanced', 'warmer'],
  },
  {
    id: 'candle-haze',
    label: 'candle haze',
    note: 'soft fire, close room',
    values: { color: 'gold', mood: 'warm', genre: 'folk' },
    focuses: ['warmer', 'balanced'],
  },
  {
    id: 'glass-morning',
    label: 'glass morning',
    note: 'light, clean, exact',
    values: { color: 'white', mood: 'focused', genre: 'classical' },
    focuses: ['focused', 'balanced'],
  },
  {
    id: 'afterhours',
    label: 'afterhours',
    note: 'late desk, dim lamps',
    values: { activity: 'late-night-work', mood: 'focused', color: 'black' },
    focuses: ['focused', 'nocturnal'],
  },
  {
    id: 'veranda-heat',
    label: 'veranda heat',
    note: 'open windows, bright evening',
    values: { country: 'brazil', mood: 'warm', genre: 'jazz' },
    focuses: ['warmer', 'balanced'],
  },
  {
    id: 'snow-hush',
    label: 'snow hush',
    note: 'still air, quiet horizon',
    values: { country: 'iceland', color: 'white', mood: 'calm', genre: 'classical' },
    focuses: ['focused', 'balanced'],
  },
  {
    id: 'neon-drizzle',
    label: 'neon drizzle',
    note: 'wet pavement, pulse and blur',
    values: { color: 'red', mood: 'dreamy', genre: 'electronic' },
    focuses: ['surprising', 'nocturnal'],
  },
  {
    id: 'velvet-room',
    label: 'velvet room',
    note: 'dim red interior, close listening',
    values: { color: 'red', mood: 'melancholic', genre: 'jazz' },
    focuses: ['warmer', 'balanced'],
  },
  {
    id: 'oceanic-mind',
    label: 'oceanic mind',
    note: 'wide calm, slow breathing',
    values: { color: 'blue', mood: 'calm', genre: 'ambient' },
    focuses: ['balanced', 'focused'],
  },
  {
    id: 'wide-screen-road',
    label: 'wide-screen road',
    note: 'horizon, motion, open frame',
    values: {
      activity: 'walking',
      country: 'united-states',
      genre: 'indie',
      lyricalTheme: 'adventure',
    },
    focuses: ['surprising', 'balanced'],
  },
  {
    id: 'postcard-memory',
    label: 'postcard memory',
    note: 'soft archive, faded travel',
    values: { country: 'france', genre: 'folk', lyricalTheme: 'memory' },
    focuses: ['balanced', 'warmer'],
  },
];
