import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import {
  buildUnifiedCatalogWithOptions,
  mapUnifiedCatalogToRuntimeCatalog,
} from '../data/catalog/source/pipeline';

const outputDir = path.resolve(process.cwd(), 'data/catalog/generated');
const outputFile = path.resolve(outputDir, 'unified-catalog.ts');

const serialize = (value: unknown): string => JSON.stringify(value, null, 2);

const buildSourceFile = (payload: {
  metadata: unknown;
  runtimeTracks: unknown;
  unifiedTracks: unknown;
}): string => {
  return `/* eslint-disable */
// This file is auto-generated by \`npm run catalog:build\`.
// Do not edit by hand.

import type { MusicCandidate } from '../../../src/features/recommendations/types';
import type {
  CatalogBuildMetadata,
  UnifiedCatalogTrack,
} from '../source/types';

export const CATALOG_BUILD_METADATA: CatalogBuildMetadata = ${serialize(payload.metadata)};

export const UNIFIED_CATALOG_TRACKS: UnifiedCatalogTrack[] = ${serialize(payload.unifiedTracks)};

export const LOCAL_CATALOG: MusicCandidate[] = ${serialize(payload.runtimeTracks)};
`;
};

const main = async (): Promise<void> => {
  const { metadata, tracks } = await buildUnifiedCatalogWithOptions({
    sourceMode: 'snapshot',
  });
  const runtimeTracks = mapUnifiedCatalogToRuntimeCatalog(tracks);

  mkdirSync(outputDir, { recursive: true });
  writeFileSync(
    outputFile,
    buildSourceFile({
      metadata,
      runtimeTracks,
      unifiedTracks: tracks,
    }),
    'utf8',
  );

  console.log(
    JSON.stringify(
      {
        output: path.relative(process.cwd(), outputFile),
        total: runtimeTracks.length,
        zh: metadata.byLanguage.zh ?? 0,
        ja: metadata.byLanguage.ja ?? 0,
        ko: metadata.byLanguage.ko ?? 0,
        sourceMode: metadata.mode,
      },
      null,
      2,
    ),
  );
};

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
